### ISSUE TITLE
secret.py file is missing

### ISSUE THREAD

**Issue by andreaspapav** [samirelanduk/samireland.com#5]
I cant setup your project to work on my local machine as there is a file missing with the database configuration and secret key etc.

**Comment by samirelanduk** [comment]
Hi Andreas, 

secrets.py is deliberately not committed, as it contains sensitive information (you can see it in .gitignore), but you can easily create your own.

Create a file called secrets.py, add it to the core directory, and add something like this:

```
import os

SECRET_KEY = "random_string_of_characters_here"

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

local = {"default": {
 "ENGINE": "django.db.backends.sqlite3",
 "NAME": os.path.join(BASE_DIR, "db.sqlite3")
}}

DATABASES = local
```

You can generate a secret key using a site like [this](https://miniwebtool.com/django-secret-key-generator/), for example, but any string is fine. The reason the database stuff is in this file is because when it points to a live database you put db passwords and stuff here (omitted from this example).

Hope this helps,
Sam

**Comment by andreaspapav** [comment]
Thank you so much for your immediate response, I am sorry that i posted an issue without trying it at all. I figured it out thanks though for the clear instructions.

Kind Regards,
Andreas

On 24 Oct 2019, at 13:32, Sam Ireland <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Andreas,

secrets.py is deliberately not committed, as it contains sensitive information (you can see it in .gitignore), but you can easily create your own.

Create a file called secrets.py, add it to the core directory, and add something like this:

import os

SECRET_KEY = "random_string_of_characters_here"

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

local = {"default": {
 "ENGINE": "django.db.backends.sqlite3",
 "NAME": os.path.join(BASE_DIR, "db.sqlite3")
}}

DATABASES = local


You can generate a secret key using a site like this<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fminiwebtool.com%2Fdjango-secret-key-generator%2F&data=02%7C01%7C%7Cd68fe9409cc94c8e3d0c08d7587e32b8%7C1faf88fea9984c5b93c9210a11d9a5c2%7C0%7C0%7C637075171348611881&sdata=2qiHNrlYL6UbcbrHKsL5xgzZIKWVs3%2B4FboSyH3e75c%3D&reserved=0>, for example, but any string is fine. The reason the database stuff is in this file is because when it points to a live database you put db passwords and stuff here (omitted from this example).

Hope this helps,
Sam
